language: node_js
node_js: stable
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
    - secure: >-
        P5nLU494iwXg/eBCBVZ87Ec1ARfk1wwUBdJI0e9tsVHAPo6HfaGG0i8xzrAQ7cDPnikosuOvipp9dzW/9LgcvBw6KoFGpLmx4KqXJ7E6VyMoMCBbOTGRy15yWPyXL8CJh2HLcl/IKEKI1v9D5nqkJNm3v6O/29+h/qqfx7wC7Q4CIHGLA5//r3l8LVGuzFw+TBcBzIA2a6j88pgGJddvbyUVmVJs9iCpppH/CaCSsQsTFgdF184FtfRJWNDhjI8931V4BMKRO+11kF2Q+dqjV++H6G8ss80MJV92yRDyhbdnhvREl5td7gRgomkwJ3AotmeD6Am7SrjIvF7yyaBXVOJ7YjvJLHwcUpAehckLFz0w/QahCZAUTH35VRU539nKEz1XdrgkuCQSD7Fvi0bv+HkH5x5uuDvVmA4x6DFuO7hEpM2JtRafbqPrYa+y9R1l7hF+N+9XblfX2vpkWpqhlZFgC0lyj8rOLuoaNwjLvsClzzfo3H7OWxWPjKnbez8b5O1QVLblhVjJ+c0wu6RGsbTbPiQU3Akbo53S/mqBNPbrZHnEkzxBmFFO1xd5Ff1fXJlHTNSPzzJCVCcH6cWbDY2cXl/BunAOi9D4wTinsKkMqwfunFW0ROvoh0j9NKHbc8xEVPV2/N1XqdjiWmi+df1769xPqDL9flHpw7qTuyw=
    - secure: >-
        m8hlqoyHOmBlcDDBBUXrkPrGmuU3UtLGIVDVg4WWRUVLV5iND00La9Zr4MslPmZNeOZ5oWhyVma8KlRAsA7uklq8vsPC/Wuxi1dH8hpykV/+tWgktsDD8f4VSbiz6Py067QAewpUU2f64YLYlwoy9KV3fWaehXjzEbBAg0xUwZVN7HRoNozyzbIg3BfxXauy7FSkBWRMNMqZXcYEkFIkhZZTdOu11GiVZ3viekkws3Pjuc/PI2GaLDAl1FHTQpKWB/NrF7vCC0ugE+MsfpV/LkH8yHjORmW7sLGSa4E4aRxCDI9+T5yRv+khLD8c6e2w4ZHBFbcgDFpWLScsyxmgjB5ONCvjtpCNw7bnAONi9eTlImpudlknVa40BezDRA6kIuSkoaOy6j/lv4+B+pLuxcW5krZOKiy/aY6llY2nt1OkmBY6DrBHnKsxUwy+t/vVJJqGAOBWlzvdIbknXIKP13z8oc7v3QjyPTPeLYBB3JurWrliSPt1Ui5K7/gZUmTNoorkrsO58eq4CFXomx9ICk5a/jIFwvA5z2rxTwtazdX+8HSQYM0kA7Pvw0amGl1lIGhlQqK0M5BDz0qhKou5yOAIHbWgm30+cYKuR//xWOgaI+QjCd++kPep0hmC8TmpaiXBeWo0G/VYHHdgcafeEKdjYzwtXJ9S3eiV8oyDdXI=
